image: gitpod/workspace-java-17

tasks:
    -   name: Build and test
        init: mvn test

    -   name: Start Postgresql
        command: docker run --name postgres-jtaf -d -p5432:5432 -e POSTGRES_DB=jtaf4 -e POSTGRES_USER=jtaf4 -e POSTGRES_PASSWORD=jtaf420 -d postgres:15.2

ports:
    -   port: 8484
        onOpen: open-browser
