instance_class: F4

runtime: java17

network:
    session_affinity: true

automatic_scaling:
    min_instances: 0
    max_instances: 1

liveness_check:
    path: "/actuator/health/liveness"

readiness_check:
    path: "/actuator/health/readiness"
