instance_class: B3

runtime: java17

network:
    session_affinity: true

manual_scaling:
    instances: 2

inbound_services:
    - warmup

liveness_check:
    path: "/actuator/health/liveness"

readiness_check:
    path: "/actuator/health/readiness"
