instance_class: F4

runtime: java17

network:
    session_affinity: true

automatic_scaling:
    min_instances: 1
    max_instances: 1

inbound_services:
    - warmup

liveness_check:
    path: "/actuator/health/liveness"

readiness_check:
    path: "/actuator/health/readiness"
