name: CI

on:
    push:
        branches-ignore: [ master ]
    pull_request:
        branches: [ develop ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'

            -   name: Cache SonarCloud packages
                uses: actions/cache@v1
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar

            -   name: Cache local Maven repository
                uses: actions/cache@v2
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: Maven Build and Sonar Checks and Create Docker Image
                run: mvn -B verify sonar:sonar -Pcoverage -Dsonar.projectKey=72services_jtaf4
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            -   name: Maven Build Docker Image
                run: mvn -B spring-boot:build-image -Pproduction -DskipTests -Dspring-boot.build-image.imageName=72services/jtaf4:latest

            -   name: Log in to Docker Hub
                uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

            -   name: Docker Push
                run: docker push 72services/jtaf4:latest
