name: CI

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'adopt'
            -   name: Cache SonarCloud packages
                uses: actions/cache@v1
                with:
                    path: ~/.sonar/cache
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Cache local Maven repository
                uses: actions/cache@v2
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-
            -   name: Maven build
                run: mvn -B verify sonar:sonar -Pcoverage -Dsonar.projectKey=72services_jtaf4
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
